# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26b7ec026aa3eb4701ae3c76852fdf2ce6705bb45a9c68f9d897b3ec36a63f996033e09b64ab6f978421f309594b87a3554b7221b890f242d3c04c2e26f53ed8

test:
  secret_key_base: ef531e6c4c020d5763ba426b820dd414a8b919112f060ff533b69662fb63e75065d7ca4b9df3c968223938fcbd436fffb8dd65f68c7459c8d6bc6aaf5ef7c8a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
